name: Test Secret

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print masked secret
      run: echo "The secret is ${{ secrets.GOOGLE_SHEET_ID }}"

    - name: Show first 5 characters (for testing only)
      run: echo "First few chars: ${GOOGLE_SHEET_ID:0:5}"
      env:
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
