name: Test Secret

on:
  workflow_dispatch:  # Allows you to run the workflow manually

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Print masked secret
      run: echo "The secret is ${{ secrets.GOOGLE_SHEET_ID }}"
