# .github/workflows/youtube-analysis.yml
name: YouTube Channel Analysis

on:
  # Trigger from Google Apps Script
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Channel URL'
        required: false
        default: ''
      triggered_by:
        description: 'Trigger source'
        required: false
        default: 'manual'
      timestamp:
        description: 'Trigger timestamp'
        required: false
        default: ''
  
  # Trigger on push to main branch (optional)
  push:
    branches: [ main ]
    paths: 
      - 'src/**'
      - '.github/workflows/**'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Check environment variables
      run: |
        echo "Checking environment setup..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "GOOGLE_INPUT_DOC_ID is set: ${{ secrets.GOOGLE_INPUT_DOC_ID != '' }}"
        echo "GOOGLE_OUTPUT_DOC_ID is set: ${{ secrets.GOOGLE_OUTPUT_DOC_ID != '' }}"
        echo "YOUTUBE_API_KEY is set: ${{ secrets.YOUTUBE_API_KEY != '' }}"
        
    - name: Run YouTube Channel Analysis
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
        GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
        GOOGLE_INPUT_DOC_ID: ${{ secrets.GOOGLE_INPUT_DOC_ID }}
        GOOGLE_OUTPUT_DOC_ID: ${{ secrets.GOOGLE_OUTPUT_DOC_ID }}
      run: |
        echo "Starting YouTube Channel Analysis..."
        mkdir -p results
        node src/analyze.js
        echo "Analysis completed."
      
    - name: Archive analysis results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: analysis-results
        path: results/
        retention-days: 30
        if-no-files-found: ignore
